/* U10 Herseaux - PWA GitHub Pages + Supabase */
const cfg = window.APP_CONFIG || {};
const configured = cfg.SUPABASE_URL && !cfg.SUPABASE_URL.includes('VOTRE-PROJET') && cfg.SUPABASE_ANON_KEY && !cfg.SUPABASE_ANON_KEY.includes('VOTRE_CLE');
const sb = configured ? window.supabase.createClient(cfg.SUPABASE_URL, cfg.SUPABASE_ANON_KEY) : null;

const state = { user:null, profile:null, membership:null, team:null, players:[], events:[], page:'dashboard', month:new Date(), installPrompt:null };
const $ = (s, r=document) => r.querySelector(s);
const $$ = (s, r=document) => [...r.querySelectorAll(s)];
const esc = (v='') => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmtDate = d => new Intl.DateTimeFormat('fr-BE',{weekday:'short',day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00'));
const fmtLong = d => new Intl.DateTimeFormat('fr-BE',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date(d+'T12:00:00'));
const timeShort = t => t ? t.slice(0,5) : '';
const todayISO = () => { const d=new Date(); return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-'); };
function toast(msg, ok=true){ const t=$('#toast'); t.textContent=msg; t.style.borderColor=ok?'#2f6d42':'#7a3434'; t.classList.add('show'); clearTimeout(t._timer); t._timer=setTimeout(()=>t.classList.remove('show'),2800); }
function setBusy(btn, busy, label='Enregistrement…'){ if(!btn)return; if(busy){btn.dataset.old=btn.textContent;btn.textContent=label;btn.disabled=true}else{btn.textContent=btn.dataset.old||btn.textContent;btn.disabled=false} }
function openModal(html){ $('#modalBody').innerHTML=html; $('#modal').classList.remove('hidden'); }
function closeModal(){ $('#modal').classList.add('hidden'); $('#modalBody').innerHTML=''; }

window.addEventListener('beforeinstallprompt', e => { e.preventDefault(); state.installPrompt=e; $('#installBtn')?.classList.remove('hidden'); });
$('#installBtn')?.addEventListener('click', async()=>{ if(state.installPrompt){ state.installPrompt.prompt(); await state.installPrompt.userChoice; state.installPrompt=null; $('#installBtn').classList.add('hidden'); }});
$('#modalClose').addEventListener('click',closeModal); $('#modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
window.addEventListener('online',()=>$('#syncState').textContent='● En ligne');
window.addEventListener('offline',()=>$('#syncState').textContent='● Hors ligne');

const NAV_COACH = [
  ['dashboard','⌂','Tableau de bord'],['calendar','▦','Calendrier'],['attendance','✓','Présences'],['players','⚽','Joueurs'],['evaluations','★','Évaluations'],['settings','⚙','Paramètres']
];
const NAV_PARENT = [['dashboard','⌂','Accueil'],['calendar','▦','Calendrier'],['attendance','✓','Présences'],['settings','⚙','Mon compte']];
const isCoach = () => state.membership?.role === 'coach';

function setView(which){ ['authView','joinView','appView'].forEach(id=>$('#'+id).classList.add('hidden')); $('#'+which).classList.remove('hidden'); }
function pageMeta(page){ const m={dashboard:['Tableau de bord','Vue d’ensemble de l’équipe'],calendar:['Calendrier','Entraînements, matchs et tournois'],attendance:['Présences','Disponibilités parents et présence réelle'],players:['Joueurs','Effectif et accès parents'],evaluations:['Évaluations','Technique, jeu, athlétique, mental & attitude'],settings:['Paramètres','Compte et accès à l’équipe']}; return m[page]||m.dashboard; }
function renderNav(){ const nav=isCoach()?NAV_COACH:NAV_PARENT; $('#nav').innerHTML=nav.map(([id,ic,lab])=>`<button class="nav-btn ${state.page===id?'active':''}" data-page="${id}"><span class="nav-icon">${ic}</span>${lab}</button>`).join(''); $$('#nav .nav-btn').forEach(b=>b.onclick=()=>go(b.dataset.page)); }
async function go(page){ state.page=page; renderNav(); const [t,s]=pageMeta(page); $('#pageTitle').textContent=t; $('#pageSubtitle').textContent=s; $('#sidebar').classList.remove('open'); if(page==='dashboard') await renderDashboard(); if(page==='calendar') await renderCalendar(); if(page==='attendance') await renderAttendance(); if(page==='players') await renderPlayers(); if(page==='evaluations') await renderEvaluations(); if(page==='settings') await renderSettings(); }

async function init(){
  if(!configured){ $('#setupWarning').classList.remove('hidden'); return; }
  const {data:{session}} = await sb.auth.getSession();
  if(session?.user) await loadUser(session.user); else setView('authView');
  sb.auth.onAuthStateChange(async(_e,session)=>{ if(session?.user && session.user.id!==state.user?.id) await loadUser(session.user); if(!session) logoutLocal(); });
}
async function loadUser(user){
  state.user=user;
  let {data:profile}=await sb.from('profiles').select('*').eq('id',user.id).maybeSingle();
  state.profile=profile||{id:user.id,full_name:user.email,role:'parent'};
  let {data:memberships,error}=await sb.from('team_members').select('team_id,role,teams(*)').eq('user_id',user.id).limit(1);
  if(error) console.error(error);
  if(!memberships?.length){ setView('joinView'); return; }
  state.membership=memberships[0]; state.team=memberships[0].teams;
  $('#seasonLabel').textContent=state.team.season||'';
  $('#userCard').innerHTML=`<strong>${esc(state.profile.full_name||user.email)}</strong><br><span class="muted">${isCoach()?'Coach':'Parent'}</span>`;
  setView('appView'); renderNav(); await loadCore(); await go(state.page);
}
async function loadCore(){
  const [{data:players},{data:events}] = await Promise.all([
    sb.from('players').select('*').eq('team_id',state.team.id).eq('active',true).order('first_name'),
    sb.from('events').select('*').eq('team_id',state.team.id).order('event_date').order('start_time')
  ]);
  state.players=players||[]; state.events=events||[];
}
function logoutLocal(){ state.user=state.profile=state.membership=state.team=null; state.players=[]; state.events=[]; setView('authView'); }

$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{ $$('[data-auth-tab]').forEach(x=>x.classList.toggle('active',x===b)); $('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login'); $('#signupForm').classList.toggle('hidden',b.dataset.authTab!=='signup'); });
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault(); const btn=e.submitter;setBusy(btn,true,'Connexion…'); const {error}=await sb.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value}); setBusy(btn,false); if(error)toast(error.message,false)});
$('#signupForm').addEventListener('submit',async e=>{e.preventDefault(); const btn=e.submitter;setBusy(btn,true); const name=$('#signupName').value.trim(); const {data,error}=await sb.auth.signUp({email:$('#signupEmail').value.trim(),password:$('#signupPassword').value,options:{data:{full_name:name}}}); setBusy(btn,false); if(error)return toast(error.message,false); if(data.user) toast('Compte créé. Vérifie ton e-mail si Supabase demande une confirmation.'); });
$('#joinTeamForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const {error}=await sb.rpc('join_team',{p_code:$('#teamCode').value.trim()});setBusy(btn,false);if(error)return toast(error.message,false);toast('Équipe rejointe');await loadUser(state.user)});
$('#claimCoachForm').addEventListener('submit',async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const {error}=await sb.rpc('claim_coach',{p_code:$('#coachCode').value.trim()});setBusy(btn,false);if(error)return toast(error.message,false);toast('Compte coach activé');await loadUser(state.user)});
$('#logoutBtn').onclick=$('#logoutJoin').onclick=()=>sb.auth.signOut(); $('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');

function eventTypePill(type){ const x={training:['green','Entraînement'],match:['blue','Match'],tournament:['orange','Tournoi'],other:['gray','Autre']}[type]||['gray',type]; return `<span class="pill ${x[0]}">${x[1]}</span>`; }
function statusPill(s){ const m={present:['green','Présent'],absent:['red','Absent'],maybe:['orange','Incertain'],excused:['orange','Excusé'],late:['orange','Retard']}; const x=m[s]||['gray','Pas de réponse']; return `<span class="pill ${x[0]}">${x[1]}</span>`; }

async function renderDashboard(){
  await loadCore(); const now=todayISO(); const upcoming=state.events.filter(e=>e.event_date>=now).slice(0,6); const thisMonth=state.events.filter(e=>e.event_date.slice(0,7)===now.slice(0,7));
  let linked=[]; if(!isCoach()){ const {data}=await sb.from('player_guardians').select('player_id,players(*)').eq('user_id',state.user.id); linked=data||[]; }
  let html=`<div class="cards"><div class="stat"><div class="label">Joueurs actifs</div><div class="value">${state.players.length}</div></div><div class="stat"><div class="label">Événements ce mois</div><div class="value">${thisMonth.length}</div></div><div class="stat"><div class="label">Prochains matchs</div><div class="value">${upcoming.filter(e=>e.type==='match').length}</div></div><div class="stat"><div class="label">Profil</div><div class="value" style="font-size:1.2rem">${isCoach()?'Coach':'Parent'}</div></div></div>`;
  if(!isCoach() && !linked.length){ html+=`<div class="notice warning"><strong>Aucun enfant lié.</strong> Demande au coach de générer un code joueur, puis utilise “Lier mon enfant” dans Mon compte.</div>`; }
  html+=`<div class="section-head"><h3>Prochains rendez-vous</h3>${isCoach()?'<button class="btn primary small" id="addEventDash">+ Ajouter</button>':''}</div><div class="event-list">${upcoming.length?upcoming.map(eventCard).join(''):'<div class="empty panel">Aucun événement à venir.</div>'}</div>`;
  $('#content').innerHTML=html; $('#addEventDash')?.addEventListener('click',()=>eventModal()); bindEventButtons();
}
function eventCard(e){ const opponent=e.opponent?` · vs ${esc(e.opponent)}`:''; return `<div class="event-card"><div class="event-title"><h4>${esc(e.title)}</h4>${eventTypePill(e.type)}</div><div class="event-meta"><span>📅 ${fmtLong(e.event_date)}</span><span>🕒 ${timeShort(e.start_time)}</span>${e.meeting_time?`<span>👥 RDV ${timeShort(e.meeting_time)}</span>`:''}${e.location?`<span>📍 ${esc(e.location)}</span>`:''}${opponent}</div>${e.notes?`<div class="muted">${esc(e.notes)}</div>`:''}<div class="event-actions"><button class="btn ghost small" data-event-presence="${e.id}">Présences</button>${isCoach()?`<button class="btn secondary small" data-edit-event="${e.id}">Modifier</button>`:''}</div></div>`; }
function bindEventButtons(){ $$('[data-event-presence]').forEach(b=>b.onclick=()=>{state.selectedEvent=b.dataset.eventPresence;go('attendance')}); $$('[data-edit-event]').forEach(b=>b.onclick=()=>eventModal(state.events.find(e=>e.id===b.dataset.editEvent))); }

async function renderCalendar(){ await loadCore(); const d=state.month; const y=d.getFullYear(),m=d.getMonth(); $('#content').innerHTML=`<div class="calendar-toolbar"><div class="toolbar-group"><button class="btn ghost small" id="prevMonth">←</button><button class="btn ghost small" id="todayMonth">Aujourd'hui</button><button class="btn ghost small" id="nextMonth">→</button></div><strong>${new Intl.DateTimeFormat('fr-BE',{month:'long',year:'numeric'}).format(d)}</strong>${isCoach()?'<button class="btn primary small" id="addEvent">+ Événement</button>':'<span></span>'}</div>${calendarHTML(y,m)}<div class="section-head"><h3>Événements du mois</h3></div><div class="event-list">${state.events.filter(e=>{const x=new Date(e.event_date+'T12:00:00');return x.getFullYear()===y&&x.getMonth()===m}).map(eventCard).join('')||'<div class="empty panel">Aucun événement.</div>'}</div>`;
  $('#prevMonth').onclick=()=>{state.month=new Date(y,m-1,1);renderCalendar()}; $('#nextMonth').onclick=()=>{state.month=new Date(y,m+1,1);renderCalendar()}; $('#todayMonth').onclick=()=>{state.month=new Date();renderCalendar()}; $('#addEvent')?.addEventListener('click',()=>eventModal()); bindEventButtons();
}
function calendarHTML(y,m){ const first=new Date(y,m,1), start=new Date(y,m,1-((first.getDay()+6)%7)); let cells=''; const names=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim']; for(let i=0;i<42;i++){ const dd=new Date(start);dd.setDate(start.getDate()+i); const iso=[dd.getFullYear(),String(dd.getMonth()+1).padStart(2,'0'),String(dd.getDate()).padStart(2,'0')].join('-'); const evs=state.events.filter(e=>e.event_date===iso); cells+=`<div class="cal-day ${dd.getMonth()!==m?'other':''}"><span class="day-num">${dd.getDate()}</span>${evs.map(e=>`<span class="cal-event ${e.type}" title="${esc(e.title)}">${timeShort(e.start_time)} ${esc(e.title)}</span>`).join('')}</div>`; } return `<div class="calendar">${names.map(n=>`<div class="cal-head">${n}</div>`).join('')}${cells}</div>`; }
function eventModal(e=null){ openModal(`<h2>${e?'Modifier':'Ajouter'} un événement</h2><form id="eventForm" class="form-grid"><label>Type<select id="evType"><option value="training">Entraînement</option><option value="match">Match</option><option value="tournament">Tournoi</option><option value="other">Autre</option></select></label><label>Titre<input id="evTitle" required value="${esc(e?.title||'')}" placeholder="Ex. Entraînement U10" /></label><label>Date<input id="evDate" type="date" required value="${e?.event_date||todayISO()}" /></label><label>Heure début<input id="evStart" type="time" required value="${timeShort(e?.start_time)||'18:00'}" /></label><label>Heure fin<input id="evEnd" type="time" value="${timeShort(e?.end_time)}" /></label><label>Heure de rendez-vous<input id="evMeet" type="time" value="${timeShort(e?.meeting_time)}" /></label><label>Lieu<input id="evLocation" value="${esc(e?.location||'')}" /></label><label>Adversaire<input id="evOpponent" value="${esc(e?.opponent||'')}" /></label><label class="full">Adresse<input id="evAddress" value="${esc(e?.address||'')}" /></label><label class="full">Informations<textarea id="evNotes">${esc(e?.notes||'')}</textarea></label><div class="full" style="display:flex;gap:8px;justify-content:flex-end">${e?'<button type="button" id="deleteEvent" class="btn danger">Supprimer</button>':''}<button class="btn primary">Enregistrer</button></div></form>`); $('#evType').value=e?.type||'training';
  $('#eventForm').onsubmit=async ev=>{ev.preventDefault();const btn=ev.submitter;setBusy(btn,true);const payload={team_id:state.team.id,type:$('#evType').value,title:$('#evTitle').value.trim(),event_date:$('#evDate').value,start_time:$('#evStart').value||null,end_time:$('#evEnd').value||null,meeting_time:$('#evMeet').value||null,location:$('#evLocation').value.trim()||null,address:$('#evAddress').value.trim()||null,opponent:$('#evOpponent').value.trim()||null,notes:$('#evNotes').value.trim()||null,created_by:state.user.id}; let q=e?sb.from('events').update(payload).eq('id',e.id):sb.from('events').insert(payload); const {error}=await q;setBusy(btn,false);if(error)return toast(error.message,false);closeModal();toast('Événement enregistré');await loadCore();await go(state.page)};
  $('#deleteEvent')?.addEventListener('click',async()=>{if(!confirm('Supprimer cet événement ?'))return;const {error}=await sb.from('events').delete().eq('id',e.id);if(error)return toast(error.message,false);closeModal();toast('Événement supprimé');await loadCore();await go(state.page)});
}

async function renderAttendance(){ await loadCore(); const upcoming=state.events.filter(e=>e.event_date>=new Date(Date.now()-7*86400000).toISOString().slice(0,10)); const selected=state.selectedEvent||upcoming[0]?.id||state.events.at(-1)?.id; state.selectedEvent=selected; if(!selected){$('#content').innerHTML='<div class="empty panel">Crée d’abord un événement.</div>';return;} const e=state.events.find(x=>x.id===selected); const opts=state.events.slice().reverse().map(x=>`<option value="${x.id}" ${x.id===selected?'selected':''}>${x.event_date} · ${esc(x.title)}</option>`).join(''); let html=`<div class="panel"><div class="form-grid"><label>Événement<select id="attendanceEvent">${opts}</select></label><div><strong>${esc(e.title)}</strong><div class="muted">${fmtLong(e.event_date)} · ${timeShort(e.start_time)} ${e.location?'· '+esc(e.location):''}</div></div></div></div>`;
  if(isCoach()) html+=await coachAttendanceHTML(e); else html+=await parentAttendanceHTML(e); $('#content').innerHTML=html; $('#attendanceEvent').onchange=ev=>{state.selectedEvent=ev.target.value;renderAttendance()}; bindAttendance();
}
async function coachAttendanceHTML(e){ const [{data:avail},{data:actual}]=await Promise.all([sb.from('availability').select('*').eq('event_id',e.id),sb.from('attendance').select('*').eq('event_id',e.id)]); const am=new Map((avail||[]).map(x=>[x.player_id,x])),tm=new Map((actual||[]).map(x=>[x.player_id,x])); return `<div class="section-head"><h3>Feuille de présence</h3><span class="muted">Réponse parent + présence constatée</span></div><div class="table-wrap"><table><thead><tr><th>Joueur</th><th>Réponse parent</th><th>Commentaire</th><th>Présence réelle</th></tr></thead><tbody>${state.players.map(p=>{const a=am.get(p.id),t=tm.get(p.id);return `<tr><td><strong>${esc(p.first_name)}</strong></td><td>${statusPill(a?.status)}</td><td>${esc(a?.comment||'')}</td><td><div class="presence-toggle" data-actual-player="${p.id}">${[['present','Présent'],['absent','Absent'],['excused','Excusé'],['late','Retard']].map(([v,l])=>`<button data-val="${v}" class="${t?.status===v?'selected '+(v==='present'?'present':v==='absent'?'absent':'maybe'):''}">${l}</button>`).join('')}</div></td></tr>`}).join('')}</tbody></table></div>`; }
async function parentAttendanceHTML(e){ const {data:links}=await sb.from('player_guardians').select('player_id,players(*)').eq('user_id',state.user.id); if(!links?.length)return `<div class="notice warning">Aucun enfant n'est encore lié à ton compte. Va dans <strong>Mon compte</strong> et utilise le code joueur donné par le coach.</div>`; const ids=links.map(l=>l.player_id); const {data:avail}=await sb.from('availability').select('*').eq('event_id',e.id).in('player_id',ids); const map=new Map((avail||[]).map(x=>[x.player_id,x])); return `<div class="section-head"><h3>Disponibilité</h3><span class="muted">À compléter avant le rendez-vous</span></div><div class="event-list">${links.map(l=>{const a=map.get(l.player_id);return `<div class="event-card"><div class="event-title"><h4>${esc(l.players.first_name)}</h4>${statusPill(a?.status)}</div><div class="presence-toggle" data-parent-player="${l.player_id}">${[['present','Présent'],['absent','Absent'],['maybe','Incertain']].map(([v,lab])=>`<button data-val="${v}" class="${a?.status===v?'selected '+v:''}">${lab}</button>`).join('')}</div><label>Commentaire<input data-comment-player="${l.player_id}" value="${esc(a?.comment||'')}" placeholder="Ex. blessure, retard…" /></label><button class="btn primary small" data-save-parent="${l.player_id}">Enregistrer</button></div>`}).join('')}</div>`; }
function bindAttendance(){ $$('[data-actual-player] button').forEach(b=>b.onclick=async()=>{const wrap=b.parentElement,pid=wrap.dataset.actualPlayer,status=b.dataset.val;const {error}=await sb.from('attendance').upsert({event_id:state.selectedEvent,player_id:pid,status,marked_by:state.user.id,updated_at:new Date().toISOString()},{onConflict:'event_id,player_id'});if(error)return toast(error.message,false);$$('button',wrap).forEach(x=>x.className='');b.className='selected '+(status==='present'?'present':status==='absent'?'absent':'maybe')}); $$('[data-parent-player] button').forEach(b=>b.onclick=()=>{const wrap=b.parentElement;$$('button',wrap).forEach(x=>x.className='');b.className='selected '+b.dataset.val;wrap.dataset.value=b.dataset.val}); $$('[data-save-parent]').forEach(b=>b.onclick=async()=>{const pid=b.dataset.saveParent,wrap=$(`[data-parent-player="${pid}"]`),status=wrap.dataset.value||$('.selected',wrap)?.dataset.val;if(!status)return toast('Choisis Présent, Absent ou Incertain.',false);const comment=$(`[data-comment-player="${pid}"]`).value.trim();setBusy(b,true);const {error}=await sb.from('availability').upsert({event_id:state.selectedEvent,player_id:pid,status,comment,set_by:state.user.id,updated_at:new Date().toISOString()},{onConflict:'event_id,player_id'});setBusy(b,false);if(error)return toast(error.message,false);toast('Disponibilité enregistrée');renderAttendance()}); }

async function renderPlayers(){ if(!isCoach()){go('dashboard');return;} await loadCore(); const {data:links}=await sb.from('player_guardians').select('player_id,user_id,profiles(full_name)'); const counts={};(links||[]).forEach(l=>counts[l.player_id]=(counts[l.player_id]||0)+1); $('#content').innerHTML=`<div class="section-head"><h3>Effectif U10</h3><button class="btn primary small" id="addPlayer">+ Joueur</button></div><div class="table-wrap"><table><thead><tr><th>Joueur</th><th>N°</th><th>Parents liés</th><th>Code parent</th><th>Action</th></tr></thead><tbody>${state.players.map(p=>`<tr><td><strong>${esc(p.first_name)} ${esc(p.last_name||'')}</strong></td><td>${p.number||'—'}</td><td>${counts[p.id]||0}</td><td><button class="btn ghost small" data-pin="${p.id}">Générer / remplacer</button></td><td><button class="btn danger small" data-disable="${p.id}">Désactiver</button></td></tr>`).join('')}</tbody></table></div>`; $('#addPlayer').onclick=()=>playerModal(); $$('[data-pin]').forEach(b=>b.onclick=()=>generatePin(b.dataset.pin)); $$('[data-disable]').forEach(b=>b.onclick=async()=>{if(!confirm('Désactiver ce joueur ?'))return;const{error}=await sb.from('players').update({active:false}).eq('id',b.dataset.disable);if(error)return toast(error.message,false);await loadCore();renderPlayers()}); }
function playerModal(){openModal(`<h2>Ajouter un joueur</h2><form id="playerForm" class="stack"><label>Prénom<input id="plFirst" required /></label><label>Nom (optionnel)<input id="plLast" /></label><label>Numéro (optionnel)<input id="plNumber" type="number" min="0" max="99" /></label><button class="btn primary">Ajouter</button></form>`);$('#playerForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const{error}=await sb.from('players').insert({team_id:state.team.id,first_name:$('#plFirst').value.trim(),last_name:$('#plLast').value.trim()||null,number:$('#plNumber').value?Number($('#plNumber').value):null});setBusy(btn,false);if(error)return toast(error.message,false);closeModal();toast('Joueur ajouté');await loadCore();renderPlayers()}}
async function generatePin(pid){ const p=state.players.find(x=>x.id===pid); const {data,error}=await sb.rpc('generate_player_pin',{p_player_id:pid}); if(error)return toast(error.message,false); openModal(`<h2>Code parent · ${esc(p?.first_name||'Joueur')}</h2><p>Communique ce code au parent. Il lui permettra de lier son compte à l'enfant.</p><div class="link-code">${esc(data)}</div><p class="muted">Un nouveau code remplace immédiatement l'ancien.</p><button class="btn primary full" id="copyPin">Copier le code</button>`); $('#copyPin').onclick=async()=>{await navigator.clipboard.writeText(String(data));toast('Code copié')}; }

async function renderEvaluations(){ if(!isCoach()){go('dashboard');return;} const date=state.evalDate||todayISO(); const {data:evals}=await sb.from('evaluations').select('*').eq('eval_date',date).in('player_id',state.players.map(p=>p.id)); const map=new Map((evals||[]).map(x=>[x.player_id,x])); const sel=(pid,field,val)=>`<select class="eval-select" data-eval="${pid}" data-field="${field}"><option value=""></option>${['A','B','C'].map(x=>`<option ${val===x?'selected':''}>${x}</option>`).join('')}</select>`; $('#content').innerHTML=`<div class="panel"><div class="form-grid"><label>Date d'évaluation<input id="evalDate" type="date" value="${date}" /></label><div><strong>Barème</strong><div class="muted">A = 3 points · B = 2 · C = 1 · Score /12</div></div></div></div><div class="section-head"><h3>Grille d'évaluation</h3><button class="btn primary" id="saveEvals">Enregistrer toutes les évaluations</button></div><div class="table-wrap"><table><thead><tr><th>Joueur</th><th>Technique<br><small>Contrôle, passe, dribble</small></th><th>Intelligence de jeu<br><small>Tête levée, choix</small></th><th>Athlétique<br><small>Vitesse, coordination</small></th><th>Mental & attitude<br><small>Écoute, engagement</small></th><th>Score /12</th><th>Niveau</th><th>Remarque</th></tr></thead><tbody>${state.players.map(p=>{const v=map.get(p.id)||{};return `<tr data-eval-row="${p.id}"><td><strong>${esc(p.first_name)}</strong></td><td>${sel(p.id,'technique',v.technique)}</td><td>${sel(p.id,'game_intelligence',v.game_intelligence)}</td><td>${sel(p.id,'athletic',v.athletic)}</td><td>${sel(p.id,'attitude',v.attitude)}</td><td class="score" data-score="${p.id}">${v.score_total??'—'}</td><td>${sel(p.id,'overall_level',v.overall_level)}</td><td><input data-remark="${p.id}" value="${esc(v.remarks||'')}" /></td></tr>`}).join('')}</tbody></table></div>`; $('#evalDate').onchange=e=>{state.evalDate=e.target.value;renderEvaluations()}; $$('[data-eval]').forEach(s=>s.onchange=()=>updateEvalScore(s.dataset.eval)); $('#saveEvals').onclick=saveEvaluations; state.players.forEach(p=>updateEvalScore(p.id)); }
function evalPoints(v){return v==='A'?3:v==='B'?2:v==='C'?1:0} function updateEvalScore(pid){ const vals=$$(`[data-eval="${pid}"]`).filter(x=>x.dataset.field!=='overall_level').map(x=>x.value); const score=vals.some(Boolean)?vals.reduce((a,v)=>a+evalPoints(v),0):'—'; $(`[data-score="${pid}"]`).textContent=score; }
async function saveEvaluations(){ const btn=$('#saveEvals');setBusy(btn,true);const date=$('#evalDate').value; const rows=state.players.map(p=>{const get=f=>$(`[data-eval="${p.id}"][data-field="${f}"]`).value||null;const vals=['technique','game_intelligence','athletic','attitude'].map(get);const any=vals.some(Boolean)||get('overall_level')||$(`[data-remark="${p.id}"]`).value.trim(); if(!any)return null; return {player_id:p.id,eval_date:date,technique:vals[0],game_intelligence:vals[1],athletic:vals[2],attitude:vals[3],score_total:vals.reduce((a,v)=>a+evalPoints(v),0),overall_level:get('overall_level'),remarks:$(`[data-remark="${p.id}"]`).value.trim()||null,evaluated_by:state.user.id,updated_at:new Date().toISOString()}; }).filter(Boolean); const {error}=rows.length?await sb.from('evaluations').upsert(rows,{onConflict:'player_id,eval_date'}):{error:null};setBusy(btn,false);if(error)return toast(error.message,false);toast('Évaluations enregistrées'); }

async function renderSettings(){ let extra=''; if(!isCoach()){ const {data:links}=await sb.from('player_guardians').select('player_id,players(first_name)').eq('user_id',state.user.id); extra=`<div class="panel"><h3>Mes enfants liés</h3>${links?.length?`<p>${links.map(x=>`<span class="pill green">${esc(x.players.first_name)}</span>`).join(' ')}</p>`:'<p class="muted">Aucun enfant lié.</p>'}<button class="btn primary" id="linkChild">Lier mon enfant</button></div>`; }
  $('#content').innerHTML=`<div class="grid2"><div class="panel stack"><h3>Mon compte</h3><label>Nom et prénom<input id="profileName" value="${esc(state.profile.full_name||'')}" /></label><label>E-mail<input value="${esc(state.user.email||'')}" disabled /></label><button class="btn primary" id="saveProfile">Enregistrer</button></div><div class="panel"><h3>Équipe</h3><p><strong>${esc(state.team.name)}</strong><br><span class="muted">Saison ${esc(state.team.season)}</span></p><p class="muted">Rôle : ${isCoach()?'Coach':'Parent'}</p>${isCoach()?'<p class="muted">Les codes équipe et coach sont définis dans Supabase. Pense à remplacer les codes par défaut après installation.</p>':''}</div></div>${extra}`; $('#saveProfile').onclick=async()=>{const name=$('#profileName').value.trim();const{error}=await sb.from('profiles').update({full_name:name}).eq('id',state.user.id);if(error)return toast(error.message,false);state.profile.full_name=name;toast('Profil enregistré')}; $('#linkChild')?.addEventListener('click',linkChildModal); }
function linkChildModal(){ openModal(`<h2>Lier mon enfant</h2><p>Choisis le joueur puis saisis le code généré par le coach.</p><form id="linkChildForm" class="stack"><label>Joueur<select id="linkPlayer">${state.players.map(p=>`<option value="${p.id}">${esc(p.first_name)}</option>`).join('')}</select></label><label>Code joueur<input id="linkPin" inputmode="numeric" maxlength="6" required /></label><button class="btn primary">Lier</button></form>`); $('#linkChildForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;setBusy(btn,true);const{error}=await sb.rpc('link_player_with_pin',{p_player_id:$('#linkPlayer').value,p_pin:$('#linkPin').value.trim()});setBusy(btn,false);if(error)return toast(error.message,false);closeModal();toast('Enfant lié au compte');renderSettings()}; }

if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.warn));
init();
